management:
  endpoints:
    web:
      exposure:
        include: health,prometheus

server:
  port: 8443
  http2:
    enabled: true
  ssl:
    key-store: /opt/user-api.p12
    key-store-password: user-api
    key-store-type: pkcs12
    key-alias: user-api
    key-password: user-api

spring:
  application:
    name: "user-api"
  jpa:
    hibernate:
      ddl-auto: update # WILL BE REMOVED WHEN LIQUIBASE IS RUNNING
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/user-api
    username: postgres
    password: postgres

chat:
  exchanges:
    output: "user-events"