management:
  endpoints:
    web:
      exposure:
        include: health,prometheus


spring:
  application:
    name: "user-api"
  jpa:
    hibernate:
      ddl-auto: update # WILL BE REMOVED WHEN LIQUIBASE IS RUNNING
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/user-api
    username: postgres
    password: postgres

chat:
  exchanges:
    output: "user-events"